// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jsx        = require("../src/Jsx.bs.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var code = "\n  let x =\n    match 42 with \n    | .1 -> 4\n    | _ -> 2\n";

var param = Jsx.rewrite(code);

if (param.tag) {
  var match = param[0][1];
  var match$1 = match[/* from */1];
  console.log("Error: " + (String(match[/* message */0]) + ("\nLine " + (String(match$1[/* line */0]) + (", column " + (String(match$1[/* column */1]) + ""))))));
} else {
  Pervasives.failwith("unreachable");
}

exports.code = code;
/* param Not a pure module */
